version: "3"

volumes:
  node_modules:
services:
  my-app-dev:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.dockerfile
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
